import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';
const $=id=>document.getElementById(id),base='./';
const scene=new THREE.Scene();scene.background=new THREE.Color('#b3c7d3');scene.fog=new THREE.FogExp2('#b3c7d3',.00045);
const camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,6000);camera.position.set(-100,595,27);
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});}catch(e){$('load-label').textContent='This device could not start WebGL. Enable hardware acceleration or use a WebGL-capable browser.';throw e;}
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('world').appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(-240,215,-533);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=5;controls.maxDistance=2400;controls.maxPolarAngle=Math.PI*.485;controls.autoRotateSpeed=.35;
const ambient=new THREE.HemisphereLight(0xd1e7ff,0x5d6b4a,.85);scene.add(ambient);
const sun=new THREE.DirectionalLight(0xfff2dd,3.1);sun.position.set(-420,520,560);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-800,right:800,top:900,bottom:-900,near:1,far:3200});sun.shadow.normalBias=.06;sun.shadow.bias=-.00008;scene.add(sun);sun.target.position.set(-240,200,-533);scene.add(sun.target);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(6000,6000),new THREE.MeshStandardMaterial({color:0x77806f,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=184;ground.receiveShadow=true;scene.add(ground);
const worldGroup=new THREE.Group();scene.add(worldGroup);
const loader=new GLTFLoader();
let world,terrainMesh=null,site,mode='orbit',ready=false,tour=false,keys={},yaw=0,pitch=0,drag=null;
const clock=new THREE.Clock(),ray=new THREE.Raycaster(),down=new THREE.Vector3(0,-1,0),hitP=new THREE.Vector3(),eyeHeight=1.68;
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>$('toast').hidden=true,5000);}
function setupMesh(root){root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const m of [].concat(o.material||[])){if(m.map)m.map.anisotropy=Math.min(renderer.capabilities.getMaxAnisotropy(),8);if(m.name.includes('Leaf')){m.side=THREE.DoubleSide;m.roughness=.92;}}}});}
function groundAt(x,z){if(!terrainMesh)return null;ray.set(new THREE.Vector3(x,600,z),down);ray.far=1500;const h=ray.intersectObject(terrainMesh,false);return h.length?h[0].point.y:null;}
async function init(){try{const [g,info]=await Promise.all([loader.loadAsync(base+'assets/howey-terrain.glb',e=>{if(e.total){$('progress').style.width=(e.loaded/e.total*90)+'%';$('load-label').textContent=`Loading the valley · ${Math.round(e.loaded/e.total*100)}%`;}}),fetch(base+'assets/site-info.json').then(r=>{if(!r.ok)throw Error('Site information missing');return r.json();})]);world=g.scene;site=info;setupMesh(world);worldGroup.add(world);world.traverse(o=>{if(o.isMesh&&/terrain/i.test(o.name))terrainMesh=o;});ready=true;$('loading').hidden=true;renderer.compileAsync(scene,camera).catch(()=>{});new RGBELoader().load(base+'assets/daylight.hdr',texture=>{texture.mapping=THREE.EquirectangularReflectionMapping;scene.environment=texture;scene.background=texture;scene.backgroundBlurriness=.03;scene.environmentIntensity=.5;scene.backgroundIntensity=.75;},undefined,()=>{});}catch(e){console.error(e);$('load-label').textContent='The world could not finish loading. Check your connection and try again.';$('retry').hidden=false;}}
$('retry').onclick=()=>location.reload();
function orientAt(target){camera.lookAt(target);const e=new THREE.Euler().setFromQuaternion(camera.quaternion,'YXZ');yaw=e.y;pitch=e.x;}
async function setMode(next){if(!ready)return;mode=next;tour=false;controls.autoRotate=false;$('tour').setAttribute('aria-pressed','false');$('tour').innerHTML='▶ <span>Fly around</span>';for(const id of ['orbit','walk']){$(id).classList.toggle('active',id===next);$(id).setAttribute('aria-pressed',id===next);}controls.enabled=next==='orbit';$('move-controls').hidden=next==='orbit';if(next==='orbit'){camera.fov=46;camera.position.set(-100,595,27);controls.target.set(-240,215,-533);controls.update();$('view-name').textContent='Clawdd Glas to the village hall, in 3D.';$('hint').textContent='Drag to orbit · Scroll to zoom · Right-drag to pan';}if(next==='walk'){camera.fov=68;const sx=-174,sz=-395;const gy=groundAt(sx,sz);camera.position.set(sx,(gy??214)+eyeHeight,sz);orientAt(new THREE.Vector3(sx+30,(gy??214)+4,sz-60));$('view-name').textContent='On the lanes of Howey.';$('hint').textContent='Drag to look · WASD / arrows to move · Shift to run';toast('Walk with WASD or the arrow buttons. Drag the scene to look around.');}}
for(const id of ['orbit','walk'])$(id).onclick=()=>setMode(id);$('reset').onclick=()=>setMode('orbit');$('tour').onclick=async()=>{if(mode!=='orbit')await setMode('orbit');tour=!tour;controls.autoRotate=tour;$('tour').setAttribute('aria-pressed',tour);$('tour').innerHTML=tour?'Ⅱ <span>Pause</span>':'▶ <span>Fly around</span>';};
const keyMap={KeyW:'forward',ArrowUp:'forward',KeyS:'back',ArrowDown:'back',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',ShiftLeft:'run',ShiftRight:'run'};
addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||$('about').open)return;if(keyMap[e.code]){keys[keyMap[e.code]]=true;if(mode!=='orbit')e.preventDefault();}});addEventListener('keyup',e=>{if(keyMap[e.code])keys[keyMap[e.code]]=false;});addEventListener('blur',()=>keys={});for(const b of document.querySelectorAll('[data-move]')){b.onpointerdown=e=>{keys[b.dataset.move]=true;b.setPointerCapture(e.pointerId);e.preventDefault();};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.move]=false;}
renderer.domElement.addEventListener('pointerdown',e=>{if(mode==='orbit')return;drag={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(!drag||mode==='orbit')return;yaw-=(e.clientX-drag.x)*.004;pitch-=(e.clientY-drag.y)*.004;pitch=Math.max(-1.4,Math.min(1.4,pitch));camera.rotation.set(pitch,yaw,0,'YXZ');drag={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',()=>drag=null);renderer.domElement.addEventListener('pointercancel',()=>drag=null);
function collides(x,z){if(!site||!site.buildings)return false;return site.buildings.some(b=>x>b.x1-1&&x<b.x2+1&&z>b.z1-1&&z<b.z2+1);}
function move(dt){let x=Number(!!keys.right)-Number(!!keys.left),z=Number(!!keys.back)-Number(!!keys.forward);if(!x&&!z)return;const speed=(keys.run?14:6)*dt,len=Math.hypot(x,z);x=x/len*speed;z=z/len*speed;const dx=x*Math.cos(yaw)+z*Math.sin(yaw),dz=-x*Math.sin(yaw)+z*Math.cos(yaw),nx=camera.position.x+dx,nz=camera.position.z+dz;if(!collides(nx,camera.position.z))camera.position.x=nx;if(!collides(camera.position.x,nz))camera.position.z=nz;const B=site.walkBounds;camera.position.x=THREE.MathUtils.clamp(camera.position.x,B.x1,B.x2);camera.position.z=THREE.MathUtils.clamp(camera.position.z,B.z1,B.z2);const gy=groundAt(camera.position.x,camera.position.z);if(gy!==null)camera.position.y=gy+eyeHeight;}
$('info').onclick=()=>$('about').showModal();$('about').querySelector('.close').onclick=()=>$('about').close();$('about').onclick=e=>{if(e.target===$('about'))$('about').close();};$('settings').onclick=()=>{$('settings-panel').hidden=!$('settings-panel').hidden;if(!$('settings-panel').hidden)$('map-panel').hidden=true;};$('mapbtn').onclick=()=>{$('map-panel').hidden=!$('map-panel').hidden;if(!$('map-panel').hidden)$('settings-panel').hidden=true;};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Fullscreen is unavailable in this browser.');}};
$('quality').onchange=e=>{const ultra=e.target.value==='ultra';renderer.setPixelRatio(Math.min(devicePixelRatio,ultra?2:1.35));sun.shadow.mapSize.set(ultra?4096:2048,ultra?4096:2048);sun.shadow.map?.dispose();sun.shadow.map=null;renderer.shadowMap.needsUpdate=true;toast(ultra?'Ultra HD enabled. Performance depends on your device.':'Balanced detail enabled.');};
$('light').onchange=e=>{const v=e.target.value;sun.color.set(v==='golden'?0xffc078:v==='evening'?0x9db8ef:0xfff2dd);sun.intensity=v==='evening'?.5:3.1;ambient.intensity=v==='evening'?.6:.85;sun.position.set(v==='golden'?-700:-420,v==='golden'?220:520,v==='evening'?900:560);scene.backgroundIntensity=v==='evening'?.14:v==='golden'?.6:.75;renderer.toneMappingExposure=v==='evening'?.85:1.18;};
$('capture').onclick=()=>{try{const ratio=renderer.getPixelRatio(),aspect=camera.aspect;renderer.setPixelRatio(1);renderer.setSize(3840,2160,false);camera.aspect=3840/2160;camera.updateProjectionMatrix();renderer.render(scene,camera);renderer.domElement.toBlob(blob=>{if(blob){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=`clawdd-glas-howey-${mode}-4k.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('Saved a 3840 × 2160 image.');}},'image/png');renderer.setPixelRatio(ratio);renderer.setSize(innerWidth,innerHeight);camera.aspect=aspect;camera.updateProjectionMatrix();}catch(e){resize();toast('Image export failed on this device.');}};
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}addEventListener('resize',resize);
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(ready){controls.target.x=THREE.MathUtils.clamp(controls.target.x,-520,60);controls.target.y=THREE.MathUtils.clamp(controls.target.y,120,280);controls.target.z=THREE.MathUtils.clamp(controls.target.z,-760,-240);if(mode==='orbit')controls.update(dt);else move(dt);$('altitude').textContent=mode==='walk'?'Street level · 1.68 m':`${Math.round(camera.position.y)} m above the valley`;$('compass').querySelector('span').style.transform=`rotate(${THREE.MathUtils.radToDeg(controls.getAzimuthalAngle())}deg)`;}renderer.render(scene,camera);}
window.worldStatus=()=>({ready,mode,buildings:site?.buildings.length,triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls,camera:camera.position.toArray()});init();animate();
